### PR TITLE
Make single Blox repo with subprojects for components

### PR DESCRIPTION
**Pull request by wjbuys**
The new repository structure for Blox will be a single Gradle multi-project build. The structure will be something like:

```
blox/blox
├── blox-data (activity implementations for dataservice)
│   └── build.gradle
├── blox-data-api (POJOs and interfaces for dataservice)
│   └── build.gradle
├── blox-frontend (implementations of FE APIs)
│   └── build.gradle
├── blox-frontend-api (FE swagger model)
│   └── build.gradle
├── blox-frontend-client (generated FE client)
│   └── build.gradle
├── blox-integ-tests (end to end integ tests)
│   └── build.gradle
├── blox-scheduling-manager (scheduling manager implementation)
│   └── build.gradle
├── build.gradle
├── README.md (from current repository)
└── settings.gradle
```

This will allow us to easily build the whole stack, and make changes across multiple projects where necessary in the early stages of development. We can potentially split the subprojects out into separate repositories later.

### CODE REVIEW

**Comment by narehayrapetyan** [comment]
* I don't think we need to prefix everything with blox.
* instead of data since it's misleading, I'd name it dataservice
* should we name the pojo/interface dirs model instead of API since it's not really the API?
* I think each service should have its own integration tests and we can have a top level end-to-end tests directory
* we can state service later

**Comment by wjbuys** [comment]
Sounds good, so how about:

```
blox/blox
├── dataservice-model
│   └── build.gradle
├── dataservice
│   └── build.gradle
├── docs
├── frontend-client (generated client)
│   └── build.gradle
├── frontend-infrastructure (cloudformation templates, deployment tasks, etc)
│   └── build.gradle
├── frontend
│   └── build.gradle
├── acceptance-tests (end to end tests for an entire deployed stack)
│   └── build.gradle
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── blox-logo.png
├── build.gradle
└── settings.gradle
```

**Comment by narehayrapetyan** [comment]
lgtm

**Comment by wjbuys** [comment]
I seem to have accidentally merged this; I'm going to go ahead and delete and recreate the branch/PR.

**Pull request merged**
