### PR TITLE
Adding scheduler API to filter environments by cluster ARN

### PR DESCRIPTION
**Pull request by poojamaiya**
#### Summary
Adds a scheduler API to filter environments by cluster ARNs (issue #58)

#### Implementation details
Uses the the existing ListEnvironments API endpoint with an additional cluster filter parameter (which when set filters the environments returned)

#### Testing

- [X] cluster-state-service binary built locally and unit-tests pass (`cd cluster-state-service; make; cd ../`)
- [X] cluster-state-service build in Docker succeeds (`cd cluster-state-service; make release; cd ../`)
- [X] daemon-scheduler binary built locally and unit-tests pass (`cd daemon-scheduler; make; cd ../`)
- [X] daemon-scheduler build in Docker succeeds (`cd daemon-scheduler; make release; cd ../`)
- [X] daemon-scheduler integration tests succeed (`cd daemon-scheduler; ECS_CLUSTER=SchedulerTest ECS_CLUSTER_ASG=scheduler-test AWS_PROFILE=event-handler AWS_REGION=us-east-1 make integ-tests; cd ../`)
- [X] daemon-scheduler e2e tests succeed (`cd daemon-scheduler; ECS_CLUSTER=SchedulerTest ECS_CLUSTER_ASG=scheduler-test AWS_PROFILE=event-handler AWS_REGION=us-east-1 make e2e-tests; cd ../`)

New tests cover the changes: yes

#### Description for the changelog
API to support filtering environments by cluster ARN

#### Licensing

This contribution is under the terms of the Apache 2.0 License: Yes

### CODE REVIEW

**Comment by kylbarnes** [comment]
Should `GET /environments?cluster={cluster}` only support searching for cluster by Arn? Should it also support searching for cluster by name? I think this param should search both forms.

**Comment by poojamaiya** [comment]
@kylbarnes The intention is to support both filtering by cluster names and ARNs with the cluster filter key. But supporting with cluster names is dependent on my PR #82 and I wanted to keep this PR independent of that.

**Comment by kylbarnes** [comment]
Ok great. Is your intention to submit a PR in the future to add support for filtering by cluster names using this same key, as i still see the regex is specifically matching the Arn in router.go?

**Comment by poojamaiya** [comment]
@kylbarnes Yup. I didnt want to add a router path when there is no backend support. I'll submit a separate PR for it.

**Pull request merged**
