### PR TITLE
Fix ability to override AWS region/profile from gradle properties

### LINKED ISSUE #316: Blox deploy region override does not work
./gradlew deploy always deploys to us-west-2 regardless of the configured region.

### PR DESCRIPTION
**Pull request by wjbuys**
Gradle requires all DSL configuration methods to be created as extension
properties, and not as a normal Groovy object. This change does that for
the `aws` configuration method used to configure the region/profile to
pass to the AWS CLI.

## Testing
```
$ ./gradlew -Pblox.region=us-east-1 -Pblox.profile=blox-buys-alpha-us-west-2 --info data-service:deploy
[... lots of output ...]
Starting process 'command 'aws''.
  Working directory: /Users/buys/workspaces/blox/blox/data-service
  Command: aws --profile blox-buys-alpha-us-west-2 --region us-east-1 cloudformation package --template-file [... snip ...]
```

Fixes #316

### CODE REVIEW

**Review by narehayrapetyan — COMMENTED** [review]
how did you test this?

**Comment by wjbuys** [comment]
Updated description with testing done.

**Comment by narehayrapetyan** [comment]
And this also works with the gradle properties file?

**Review by narehayrapetyan — APPROVED** [review]

**Comment by wjbuys** [comment]
Yep, those look identical to `-Pkey=value` properties from the perspective of build logic.

**Pull request merged**
